version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '27081:80'
    container_name: wxcloud_wxcloudrun-express
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=wxcloudrun-express
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=feiSu0327
      - MYSQL_ADDRESS=10.21.112.171:3306
networks:
  default:
    external:
      name: wxcb0
